name: Find secrets

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get branch sha
      id: branch_sha
      run: |
        echo ${{ secrets.MAVEN_USERNAME }}
